/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rytheturtle.demo.optional;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PersonUtilTest {
    @Test void someLibraryMethodReturnsTrue() {
         
        assertTrue(PersonUtil.isEmailValidated(null), " should return 'true'");
    }
}
