/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rytheturtle.demo.optional;

public class PersonUtil {

    public static boolean isEmailValidated(Person person) {
        return true;
    }

}
