/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rytheturtle.demo.optional;


public class UserUtil {

    public static boolean isEmailValidated(User user) {
        return true;
    }

}
